version: "3"
services:
  ferry:
    build: .
    environment:
    - FERRY_DB_USER=${FERRY_DB_USER}
    - FERRY_DB_PASS=${FERRY_DB_PASS}
    - FERRY_DB_HOST=${FERRY_DB_HOST}
    volumes:
    - ~/certs/ferry_cert.pem:/home/ferry/.cert/hostcert.pem
    - ~/certs/ferry_key.pem:/home/ferry/.cert/hostkey.pem
    - ./API/src/default.yaml:/home/ferry/default.yaml
    network_mode: "bridge"
    restart: always
    ports:
    - "8443:8443"
