version: "3"
services:
  ferry:
    build: .
    environment:
    - FERRY_DB_USER=${FERRY_DB_USER}
    - FERRY_DB_PASS=${FERRY_DB_PASS}
    - FERRY_DB_HOST=${FERRY_DB_HOST}
    - FERRY_DB_NAME=${FERRY_DB_NAME}
    - FERRY_DB_PORT=${FERRY_DB_PORT}
    volumes:
    - ~/certs/ferry_cert.pem:/home/ferry/.cert/hostcert.pem
    - ~/certs/ferry_key.pem:/home/ferry/.cert/hostkey.pem
    - ./API/src/default.yaml:/home/ferry/default.yaml
    network_mode: "bridge"
    restart: always
    ports:
    - "8443:8443"
  postgres-exporter:
    image: wrouesnel/postgres_exporter
    network_mode: "bridge"
    environment:
    - DATA_SOURCE_URI=${FERRY_DB_HOST}:${FERRY_DB_PORT}/ferry_prd?sslmode=disable
    - DATA_SOURCE_USER=${FERRY_DB_USER}
    - DATA_SOURCE_PASS=${FERRY_DB_PASS}
    ports:
    - "9187:9187"
