version: "3"
services:
  ferry:
    build: .
    environment:
    - FERRY_DB_USER=${FERRY_DB_USER}
    - FERRY_DB_PASS=${FERRY_DB_PASS}
    - FERRY_DB_HOST=${FERRY_DB_HOST}
    - FERRY_DB_NAME=${FERRY_DB_NAME}
    - FERRY_DB_PORT=${FERRY_DB_PORT}
    volumes:
    - ~/certs/ferry_cert.pem:/home/ferry/.cert/hostcert.pem
    - ~/certs/ferry_key.pem:/home/ferry/.cert/hostkey.pem
    - ./API/src/default.yaml:/home/ferry/default.yaml
    network_mode: "bridge"
    restart: always
    ports:
    - "${FERRY_API_PORT}:8443"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
  postgres-exporter:
    image: wrouesnel/postgres_exporter
    network_mode: "bridge"
    restart: always
    environment:
    - DATA_SOURCE_URI=${FERRY_DB_HOST}:${FERRY_DB_PORT}/ferry_prd?sslmode=disable
    - DATA_SOURCE_USER=${FERRY_DB_USER}
    - DATA_SOURCE_PASS=${FERRY_DB_PASS}
    ports:
    - "9187:9187"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
  ferry-ingest:
    build:
      context: .
      dockerfile: Dockerfile-cron
    environment:
    - FERRY_API_HOST=https://${FERRY_API_HOST}:${FERRY_API_PORT}/
    volumes:
    - ~/certs/ferry_cert.pem:/home/ferry/hostcert.pem
    - ~/certs/ferry_key.pem:/home/ferry/hostkey.pem
    - /etc/grid-security/certificates/InCommon-IGTF-Server-CA.pem:/home/ferry/InCommon-IGTF-Server-CA.pem
    network_mode: "host"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

