log:
  file: ferry.log
  level: info

database:
  host: fermicloud051.fnal.gov
  name: ferry
  user: ferry
  password: ferry5634
  timeout: 60
  sslmode: verify-full 
  certificate: /etc/grid-security/certificates/cilogon-osg.pem

server:
  port: 8443
  cert: /home/ferry/.cert/hostcert.pem
  key: /home/ferry/.cert/hostkey.pem
  dnlist: myDN.list

certificates:
  - /etc/grid-security/certificates/cilogon-osg.pem
  - /etc/grid-security/certificates/cilogon-basic.pem
# - /etc/pki/tls/certs/ca-bundle.crt  

whitelist:
  - 131.225.154.186