log:
  file: ferry.log
  level: info

database:
  host: REPLACE
  name: REPLACE
  user: REPLACE
  password: REPLACE
  timeout: 60
  sslmode: verify-full 
  certificate: /etc/grid-security/certificates/cilogon-osg.pem

server:
  port: 8443
  cert: /home/ferry/.cert/hostcert.pem
  key: /home/ferry/.cert/hostkey.pem
  dnlist: myDN.list

certificates:
  - /etc/grid-security/certificates/cilogon-osg.pem
  - /etc/grid-security/certificates/cilogon-basic.pem
# - /etc/pki/tls/certs/ca-bundle.crt  

whitelist:
  - 131.225.154.186
  - 131.225.240.59
  - 131.225.27.36
  - 131.225.27.37
  - 131.225.193.77
  - 131.225.240.123
