#! /bin/bash
set +x

# This crude script is for the ferry_dev and ldap-text.  NEVER PRODUCTION!!!!
# It will delete all users where "objectCalls=organizationalPerson" from LDAP, leaving the one required record.
# It is intended to be run after data in ferry_prd data is pushed to ferry_dev.  After runnig this, you must run
# syncLdapToFerry, the API, to load LDAP with the correct voPersonIDs for each individual in ferry_prd.

## You will need to change the password file locations for ldap-test in this file..
## It will take some time to delete every record from LDAP as it is simply slow.

# Change this to where YOU have the passwords kept.
READDNPASSWORD="$HOME/.ldap/cilogon-ldap-test-readonly.password"
WRITEDNPASSWORD="$HOME/.ldap/cilogon-ldap-test.password"

# The ci people need an account to test with.  It is not in ferry so don't delete it.
ACCOUNT_TO_KEEP="FNALcilogontest"
LDAPSERVER="ldaps://ldap-test.cilogon.org"
# Need to use the readdn to get the data as the writedn has a limit on how many records it will return.
READDN="uid=readonly_user,ou=system,o=Fermilab,o=CO,dc=cilogon,dc=org"
WRITEDN="uid=write_user,ou=system,o=Fermilab,o=CO,dc=cilogon,dc=org"
BASEDN="ou=people,o=Fermilab,o=CO,dc=cilogon,dc=org"

# list of the voPersonIds to delete
VOFILE="/tmp/vofile-$$.txt"
# list of the voPersonIds to delete - formatted for the ldapmodify command to work
DELFILE="/tmp/vofile-del-list-$$.txt"

# Get the voPersonID of the account to keep from ldap.
VOTOKEEP=`ldapsearch -LLL -H $LDAPSERVER -D $READDN  -x -y $READDNPASSWORD -b $BASEDN "(voPersonID=$ACCOUNT_TO_KEEP)" | grep voPersonID | grep -v "dn:" | cut -d ' ' -f 2`

# Get voPersonIDs for ALL the user accounts in LDAP.  Remove the one account to keep.
ldapsearch -LLL -H $LDAPSERVER -D $READDN  -x -y $READDNPASSWORD -b $BASEDN "(objectClass=organizationalPerson)" | grep "dn:" | grep -v $VOTOKEEP | cut -d ' ' -f 2 > $VOFILE

while read DN; do
  printf "$DN\n" >> $DELFILE
done <$VOFILE

CNT=`wc -l $VOFILE | cut -d ' ' -f 1`
echo "$CNT user to be droped, which will take a while."
read -p "Type YES to continue: " CONTINUE

if [ "$CONTINUE" != "YES" ]; then
    echo "I quit!"
    ldapsearch -LLL -H $LDAPSERVER -D $READDN  -x -y $READDNPASSWORD -b $BASEDN "(objectClass=organizationalPerson)"
    exit
fi

ldapdelete -H $LDAPSERVER -D $WRITEDN -v -x -y $WRITEDNPASSWORD -f $DELFILE

printf "\n Displaying all \"objectCalls=organizationalPerson\".\n There should be one and only one."

ldapsearch -LLL -H $LDAPSERVER -D $READDN  -x -y $READDNPASSWORD -b $BASEDN \"(objectClass=organizationalPerson)\"
