log:
  level: info
  file:

database:
  host:
  port:
  name:
  user:
  password:
  timeout: 60
  sslmode: disable
  # certificate: /etc/grid-security/certificates/cilogon-osg.pem
  certificate: /home/dbiapp/local/etc/grid-security/certificates/cilogon-osg.pem
  max_open_conns: 200
  max_idle_conns: 0

server:
  port: 8445
  cert: /home/dbiapp/www/certs/ferry/dbweb6.fnal.gov-cert.pem
  key: /home/dbiapp/www/certs/ferry/dbweb6.fnal.gov-key.pem
  cas: /home/dbiapp/local/etc/grid-security/certificates/

certificates:
  - /home/dbiapp/local/etc/grid-security/certificates/cilogon-basic.pem
  - /home/dbiapp/local/etc/grid-security/certificates/cilogon-silver.pem
  - /home/dbiapp/local/etc/grid-security/certificates/InCommon-IGTF-Server-CA.pem
  #- /home/dbiapp/local/etc/grid-security/certificates/DigiCertSHA2HighAssuranceServerCA.pem
  - /home/dbiapp/local/etc/grid-security/certificates/DigiCertHighAssuranceEVRootCA.pem

ip_whitelist:

dn_whitelist:

dn_roles:

ip_roles:
