

CREATE  TABLE "public".user_archives (
	id                   integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	uid                  bigint  NOT NULL ,
	uname                varchar(100)  NOT NULL ,
	user_data            json  NOT NULL ,
	date_deleted         timestamptz DEFAULT current_timestamp NOT NULL ,
	CONSTRAINT pk_deleted_users_id PRIMARY KEY ( id )
 ) ;

\i grants.sql
