

CREATE  TABLE "public".accessors (
	accid                bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name                 text  NOT NULL ,
	active               boolean DEFAULT true NOT NULL ,
	"write"              boolean DEFAULT false NOT NULL ,
	"type"               text  NOT NULL ,
	last_updated         timestamptz DEFAULT current_timestamp NOT NULL ,
	last_used            timestamptz DEFAULT '1/1/1970' NOT NULL ,
	comments             text   ,
	CONSTRAINT pk_accessors_accid PRIMARY KEY ( accid ),
	CONSTRAINT unq_accessors UNIQUE ( name )
 ) ;

ALTER TABLE "public".accessors ADD CONSTRAINT check_type CHECK ( type::text = any (array['dn_role'::character varying, 'ip_role'::character varying, 'dn_;whitelist'::character varying, 'ip_whitelist'::character varying]::text[])  ) ;

COMMENT ON COLUMN "public".accessors.name IS 'DN or IP Address';

CREATE TRIGGER accessors_common_update_stamp BEFORE INSERT OR UPDATE ON accessors
    FOR EACH ROW EXECUTE PROCEDURE common_update_stamp();

\i grants.sql
