
CREATE SEQUENCE "public".ldap_vopersonid_seq start with 1;

ALTER TYPE external_affiliation_attribute_attribute_type ADD VALUE 'voPersonID';

--

CREATE  TABLE "public".capability_sets (
	setid                integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name                 text  NOT NULL ,
	last_updated         timestamptz DEFAULT ('now'::text)::date NOT NULL ,
	CONSTRAINT pk_capability_sets_setid PRIMARY KEY ( setid )
 ) ;

CREATE  TABLE "public".scopes (
	scopeid              bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	setid                integer  NOT NULL ,
	pattern              text  NOT NULL ,
	last_updated         timestamptz  NOT NULL ,
	CONSTRAINT pk_scopes_scopeid PRIMARY KEY ( scopeid )
 ) ;

ALTER TABLE "public".capability_sets ADD CONSTRAINT unq_capability_sets UNIQUE ( name ) ;

ALTER TABLE "public".scopes ADD CONSTRAINT unq_scopes UNIQUE ( setid, pattern ) ;

ALTER TABLE "public".scopes ADD CONSTRAINT fk_scopes_capability_sets FOREIGN KEY ( setid ) REFERENCES "public".capability_sets( setid )   ;

ALTER TABLE "public".grid_fqan ADD setid integer   ;

ALTER TABLE "public".grid_fqan ADD CONSTRAINT fk_grid_fqan_capability_sets FOREIGN KEY ( setid ) REFERENCES "public".capability_sets( setid )   ;


CREATE TRIGGER capability_sets_common_update_stamp BEFORE INSERT OR UPDATE ON capability_sets
    FOR EACH ROW EXECUTE PROCEDURE common_update_stamp();

CREATE TRIGGER scopes_common_update_stamp BEFORE INSERT OR UPDATE ON scopes
    FOR EACH ROW EXECUTE PROCEDURE common_update_stamp();

\i grants.sql
