
CREATE SEQUENCE "public".ldap_vopersonid_seq start with 1;

ALTER TYPE external_affiliation_attribute_attribute_type ADD VALUE 'voPersonId';

--

CREATE  TABLE "public".capabililty_sets (
	setid                integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name                 text  NOT NULL ,
	definition           text  NOT NULL ,
	active               boolean DEFAULT true NOT NULL ,
	last_updated         timestamptz DEFAULT ('now'::text)::date NOT NULL ,
	CONSTRAINT pk_capabililty_sets_setid PRIMARY KEY ( setid )
 ) ;

CREATE  TABLE "public".scopes (
	scopeid              bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	setid                integer  NOT NULL ,
	pattern              text  NOT NULL ,
	last_updated         timestamptz  NOT NULL ,
	CONSTRAINT pk_scopes_scopeid PRIMARY KEY ( scopeid )
 ) ;

ALTER TABLE "public".capabililty_sets ADD CONSTRAINT unq_capabililty_sets UNIQUE ( name ) ;

ALTER TABLE "public".scopes ADD CONSTRAINT unq_scopes UNIQUE ( scopeid, pattern ) ;

ALTER TABLE "public".scopes ADD CONSTRAINT fk_scopes_capabililty_sets FOREIGN KEY ( setid ) REFERENCES "public".capabililty_sets( setid )   ;

ALTER TABLE "public".grid_fqan ADD setid integer   ;

ALTER TABLE "public".grid_fqan ADD CONSTRAINT fk_grid_fqan_capabililty_sets FOREIGN KEY ( setid ) REFERENCES "public".capabililty_sets( setid )   ;


\i grants.sql
