
CREATE  TABLE "public".allocations (
	allocid              integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY  ,
	groupid              integer  NOT NULL  ,
	fiscal_year          integer  NOT NULL  ,
	"type"               text  NOT NULL  ,
	original_hours       double precision  NOT NULL,
	CONSTRAINT pk_allocations PRIMARY KEY ( allocid )
 ) ;

CREATE  TABLE "public".adjustments (
	allocid              integer  NOT NULL  ,
	create_date          date DEFAULT CURRENT_DATE NOT NULL  ,
	hours_adjusted       double precision  NOT NULL  ,
	comments             text    ,
	CONSTRAINT pk_adjustments PRIMARY KEY ( allocid, create_date )
 ) ;

ALTER TABLE "public".allocations ADD CONSTRAINT fk_allocations_groups FOREIGN KEY ( groupid ) REFERENCES "public".groups( groupid )   ;

ALTER TABLE "public".allocations ADD CONSTRAINT unq_allocations UNIQUE ( groupid, fiscal_year, type );

ALTER TABLE "public".allocations ADD CONSTRAINT check_type CHECK ( ( (type = 'cpu'::text) OR (type = 'gpu'::text)) );


ALTER TABLE "public".adjustments ADD CONSTRAINT fk_adjustments_allocations FOREIGN KEY ( allocid ) REFERENCES "public".allocations( allocid )   ;


\i grants.sql
